import type { Metadata } from "next";
import { Karla } from "next/font/google";
import "../globals.css";
import Providers from "@/provider/provider";
import { Toaster } from "sonner";


const inter = Karla({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "auth exbakx",
  description: "Generated by DeliverSync Platform",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              const originalError = console.error;
              console.error = function(...args) {
                if (typeof args[0] === 'string' && (args[0].includes('Hydration') || args[0].includes('Minified React error #418') || args[0].includes('Minified React error #423'))) {
                  return;
                }
                originalError.apply(console, args);
              };
            `,
          }}
        />
      </head>
      <body
        className={`${inter.className} antialiased bg-[#F8F8F8]`}
        suppressHydrationWarning
      >
        <Providers>
          <Toaster />
          {children}
        </Providers>
      </body>
    </html>
  );
}