
import type { Metadata } from "next";
import { Karla } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/shareUi/navbar";
import Footer from "@/components/shareUi/footer";
import Providers from "@/provider/provider";
import { Toaster } from "sonner";


const inter = Karla({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  // title: "DeliverSync Platform",
  description: "Generated by DeliverSync Platform",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <Providers>
          <Navbar />
          <Toaster />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}